version: "3.8"

services:

  mariadb:
    restart: unless-stopped
    image: mariadb:10.5
    ports:
      - 3306:3306
    volumes:
      - ./mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=sum
      - MYSQL_USER=sum_user
      - MYSQL_PASSWORD=sum_pass
    logging:
      driver: "json-file"
      options:
        max-size: "50k"

  xmysql:
    restart: unless-stopped
    build:
      context: ./xmysql
    command: ["-h", "mariadb", "-d", "sum", "-u", "sum_user", "-p", "sum_pass", "--ipAddress", "0.0.0.0"]
    ports:
      - 3307:3000
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
